### ISSUE TITLE
テンプレートエンジン決める

### ISSUE THREAD

**Issue by mactkg** [keitalab/website#5]
## 要件
- gulp使うのでどうせなら全部nodeだと楽ちんではないか
- extendの機能が必要(レイアウトのテンプレを引き継いでmain部分だけ書き込む機能)
- きちんと最近もメンテされている
## 候補
- jade
  - HTML覚えたての子が触れるかな
  - sassとか入れてる時点でもう...
- ejs
  - extend的 なことはデフォで出来ない
  - `ejs-local`とか使うっぽい
- ect
  - メンテされてない

だいたいこんなところでしょうか，なにかオススメあったらください @62grow2e @kvvzr

**Comment by mactkg** [comment]
- dustjs
  - https://github.com/linkedin/dustjs
  - ejs-localsに行くとectかこれ使えって書いてある．これでいいかも

**Comment by mactkg** [comment]
今晩dest試す．

**Comment by mactkg** [comment]
- nunjuck
  - https://github.com/mozilla/nunjucks
  - mozillaがやっているやつ．
  - swig https://github.com/paularmstrong/swig が良さそうだと思ったけどメンテ終了してた．
  - jinja2っぽくて僕は好き．
  - gulp用 https://github.com/sindresorhus/gulp-nunjucks

**Comment by mactkg** [comment]
とりあえずnunjuckでどうでしょーということで適用した

**Comment by odkey** [comment]
mergeした

**Comment by odkey** [comment]
projectについて、個別のページを作りたいので、そのテンプレ用意するのが良さそう。
でも眠いので今日はやらない（やってくれたっていいんだからね）

**Comment by mactkg** [comment]
> projectについて、個別のページを作りたいので、そのテンプレ用意するのが良さそう。

これは別Issueでいきましょう
